---
abstract: 'a POE Component that implements send_nsca functionality'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-NSCA
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  POE: 0.38
  POE::Filter::Stream: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.14
