---
abstract: 'a POE Component that implements send_nsca functionality'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-NSCA
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Component::Client::NSCA:
    file: lib/POE/Component/Client/NSCA.pm
    version: 0.16
requires:
  POE: 0.38
  POE::Filter::Stream: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  perl: 5.8.0
resources:
  homepage: http://github.com/bingos/poe-component-client-nsca/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-client-nsca.git
version: 0.16
